language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: TLYEXb9pshsDcvJUvXmHjUulF3iVDwrd4EWM7ysqkLQftrURhsDUsiUyNFmIdtvdJJrSr+HeYH6RwWrzAe0q9VAu/ar5QXs7Xbubq72O0FupBrCJ24Vs9SO3rprn5UFpPC9U9DWS1GER/ZGOg6dE2EWLM6vSbFCQ0B43IRJ1C4hw9WB6shMEEjruMWv67l4aYmHkn6xGP1AOTHQIsgZ7e3gyo4J8jqgljgAgs25HtMi7fLwcKFVOKR5PWMM0JPNPnnC4aB/6p2vqjejYLC366M96fbFh7RZvTEh7vGXxJyWVkl1rkfFFUAdUvCG5JlDxD/i8d66nUj3lWUz3ratYuRwPFPJ0+K6F+xMDaSqx7befa8COoHYDra71n1JutwbQvlt0gxzwzSkCo74LCzpLo3IYxXX4rNFULLEgWwxI82MAX0n0n2UlXqwpOGBma8R0nYNVpi9hjSf/ttrKZuCLlpVUss2KxiwClYMQOZMrYzmFhLeZEi4hrgKDaiOpL51wdcs8b+//LGVyUI2E1uKPpsSffVBdN+VHD46RVRBujK+jPBJ5UsljqAmq3tds191BIeVZ1hROg6NalnpJPsB/b1wALX+IZy28PxkpFZvlzLNwrHREMuqoT9dSewr/yI+vRVYuzXuJU9kYJiMtNYXurMZBrSWAHvd5R8KmsCjNUTA=
  app: ancient-journey-31169
  on:
    repo: Robb42/blog-app-mongoose-challenge-solution
